name: pontibus
channels:
  - conda-forge
dependencies:
  - pip
  - openff-toolkit >0.16.0
  - openff-interchange >=0.5
  - openff-nagl-base >=0.3.3
  - openff-packmol
  # packmol from ambertools 25+ hangs in tests
  - ambertools <25
  # OpenFE stack deps
  - gufe >=1.13
  - openfe >=1.13
  # Testing deps
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
