name: pontibus-docs
channels:
- conda-forge
dependencies:
- autodoc-pydantic >= 2.1

- networkx
- packaging
- plugcli
- python=3.12
- sphinx ==7.2.6 # TODO: debug "duplicate object" warning with later versions
- sphinx-click

- gitpython
- libsass
- nbsphinx
- nbsphinx-link
- myst-parser
- openff-toolkit-base == 0.17.0
- openff-units == 0.3.1
- openmm == 8.3.1
- pip
- pydantic >=2.0.0, <2.12.0  # https://github.com/openforcefield/openff-interchange/issues/1346
# These are added automatically by RTD, so we include them here
# for a consistent environment.
- mock
- pillow
- pip:
  - git+https://github.com/OpenFreeEnergy/openfe@v1.8.1
  - git+https://github.com/OpenFreeEnergy/gufe@v1.7.0
  - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@v0.3.1
  # pip install these so that we can make sure docs build on main while these packages' docs are under development
  - git+https://github.com/OpenFreeEnergy/kartograf@main
  - git+https://github.com/OpenFreeEnergy/konnektor@main
  - git+https://github.com/OpenFreeEnergy/lomap@main

