name: docs
channels:
- conda-forge
dependencies:
- autodoc-pydantic<2.0
- openfe>=1.1.0
- packaging
- plugcli
- python=3.10
- sphinx  #<7
- gitpython
- libsass
- nbsphinx
- nbsphinx-link
- myst-parser
- pip:
  - sphinx-design
  - sphinx-toolbox
  - sphinx  #<7
  - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@main

# These are added automatically by RTD, so we include them here
# for a consistent environment.
- mock
- pillow
- sphinx
- sphinx_rtd_theme
