name: pontibus-docs
channels:
- conda-forge
dependencies:
# strict pinning to avoid excessive memory error on RTD
- autodoc-pydantic==2.1.0
- openfe==1.8.1
- packaging
- plugcli
- python=3.11
- sphinx
- sphinx-click
- gitpython
- libsass
- nbsphinx
- nbsphinx-link
- myst-parser
- pip:
  - sphinx-design
  - sphinx-toolbox
  - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@main

# These are added automatically by RTD, so we include them here
# for a consistent environment.
- mock
- pillow
